""" Add SOTA models here
- add models (Rev1): CTGAN (https://github.com/sdv-dev/CTGAN), TVAE, TabDDPM 
- use `sdv` package to implement CTGAN and TVAE
- check how to implement TabDDPM

* ---NOT REALLY--- the data used in TabDDPM is the same as the one used in HardVAE, so we can use the same preprocessed data for training TabDDPM is uploaded to dropbox:
https://www.dropbox.com/scl/fi/nfwljijpqzjsxbm8znesl/data.tar?rlkey=yzcncwye2jmua9b2o1pb1zj0m&e=1&dl=0

* ---NEW--- divide the data into train/val/test to be able to tune the classifiers
* ---NEW--- add the XGBoost classifier with hyperparameter tuning to evaluate the performance of the synthetic data generated by the SOTA models and compare it with the performance of the synthetic data generated by HardVAE

* Check TabSyn repository for simple implementation of TabDDPM and TabSyn
|-- From Diffusion Models will be applied both TabSyn and TabDDPM

* ---QUESTION--- preprocessing justification
* ---Topological fidelity---


=> Now implement CTGAN and TVAE using `sdv` package and check how to implement TabDDPM. 
Then, evaluate the performance of the synthetic data generated by these models using XGBoost classifier with hyperparameter tuning 
and compare it with the performance of the synthetic data generated by HardVAE.

CHECK THSI https://github.com/MinkaiXu/TabDiff/

**NOTE** check the ctgan library directly for more control, or use directly the ctgan via sdv! <<https://github.com/sdv-dev/CTGAN>>
"""
# REQUIREMENTS:
import pandas as pd
from sdv.single_table import  CTGANSynthesizer #, TVAESynthesizer
from sdv.metadata import SingleTableMetadata
import random
from sklearn.model_selection import train_test_split
import torch
import numpy as np
import itertools
from load_data import load_data
import json
from utils import preprocess_data

#----------------------------------------
# SETTINGS
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {DEVICE}")

# # Number of RUNS = 10
# N_RUNS = 1 # FOR TESTING PURPOSES, CHANGE TO 10 LATER
# # learning rate for the synthesizers
# LEARNING_RATE = 1e-3
# ###### from cvae_hardness_integration #################
# N_EPOCHS = 150  # Total number of epochs for training
# BATCH_SIZE = 32
# CURRICULUM_EPOCHS = (N_EPOCHS*0.3, N_EPOCHS*0.3, N_EPOCHS*0.4)  # Epochs for each hardness strategy
# MASTER_SEED = 42  # Master seed for reproducibility
# random.seed(MASTER_SEED)  # Random state for reproducibility
# random_seeds = random.sample(range(1, 10**6), 1)  # Random seeds for different runs FIX IT TO 5 RANDOM SEEDS
# #----------------------------------------

# solution for reproducibility in sdv synthesizers => Perfectly reproducible through setting the random seed for both numpy and torch
def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

#------------------------------------------


# --------------------------------------------------------------------
# CTGAN via SDV
# --------------------------------------------------------------------
def ctgan(df_train, y_train,  epochs, batch_size, seed):
    set_seed(seed=seed)
    # Identify labels
    label_counts = pd.Series(y_train).value_counts()
    minority_label = label_counts.idxmin()
    majority_label = label_counts.idxmax()
    n_samples = label_counts[majority_label] - label_counts[minority_label]
    
    df_train_full = df_train.copy()
    df_train_full['Outcome'] = y_train
    df_minority = df_train_full[df_train_full['Outcome'] == minority_label]

    metadata = SingleTableMetadata()
    metadata.detect_from_dataframe(df_train_full)

    ctgan = CTGANSynthesizer(metadata, epochs=epochs, batch_size=batch_size, enable_gpu=torch.cuda.is_available(), verbose=True, pac=8) # selected according to the batch size
    ctgan.fit(df_minority)
    ctgan_samples = ctgan.sample(n_samples)

    X_ctgan = ctgan_samples.drop(columns = ['Outcome'])
    y_ctgan = np.full(len(X_ctgan), minority_label)
    return X_ctgan, y_ctgan


# # this is how it can be used -> later make in a function/class use it in HardVAE class
# dataset_names = ['BCWDD'] #, 'HeartCleveland', 'Hepatitis', 'Hypothyroid', 'ILPD',  'NewThyroid1', 'NewThyroid2', 'Pima', 'Thoracic', 'Vertebral']

# for dataset_name, seed in itertools.product(dataset_names, random_seeds):    # and random seed in random seeds so it is a tuple
    
#     # load the dataframe:
#     dataframe = pd.read_csv(rf'C:\Users\MABROUKAs\Downloads\IEEE-Access-2026\HardVAE\data\processed\{dataset_name}.csv')
#     print(f"{dataframe.columns.tolist()}")
#     df_base = dataframe.iloc[:, :-1]
#     print(f"df_base\n {df_base.head()}")
#     df_labels = dataframe.iloc[:, -1]
#     print(f"df_labels\n {df_labels.head()}")

#     DATA_PATH = fr'C:\Users\MABROUKAs\Downloads\IEEE-Access-2026\HardVAE\data\processed\{dataset_name}.csv'

#     # split the data into train/val/test sets 24/04/2026
#     X_train, y_train, X_val, y_val, X_test, y_test= load_data(DATA_PATH, random_state=seed )
    
#     # preprocessor
#     processor = preprocess_data(random_state=seed)
#     X_train_proc, df_train_proc = processor.fit_transform(X_train=X_train)
#     X_val_proc, _ = processor.transform(X_val)
#     X_test_proc, _ = processor.transform(X_test)

#     print(f"Type of X_train is {type(X_train)}")

#     # Indentify majority and minority classes
#     label_counts = pd.Series(y_train).value_counts()
#     print(label_counts)
#     minority_label = label_counts.idxmin()
#     print(f"Minority label: {minority_label}")
#     majority_label = label_counts.idxmax()
#     print(f"Majority label: {majority_label}")

#     # get the number of samples needed to balance the training data
#     minority_count = label_counts[minority_label]
#     majority_count = label_counts[majority_label]
#     # imbalance_ratio = minority_count / (majority_count)
#     # number of samples needed to balance the training data
#     n_samples_needed = majority_count - minority_count

#     print(f"Number of samples needed to balance the training data: {n_samples_needed}")
#     print(f"shape of X_train = {X_train.shape}")
#     print(f"columns = {X_train.columns}")

#     print(f"type of df_train_proc {type(df_train_proc)}")
#     print(f"head of df_train_proc: {df_train_proc.head()}")
#     print(f"columns of df_train_proc: {df_train_proc.columns}")
#     df_train_full = df_train_proc.copy()
    
#     df_train_full['Outcome'] = y_train.values if hasattr(y_train, 'values') else y_train
#     df_minority = df_train_full[df_train_full['Outcome'] == minority_label]

#     print(f"train data head: \n{df_train_full.head()}")
#     print(f"df_train info: \n{df_train_full.info()}")

#     # # Separate the training data into majority and minority classes
#     # df_minority = df_train_full[df_train_full['Outcome'] == minority_label]
#     # print(f"minority class count: {len(df_minority)}")
#     # df_majority = df_train_full[df_train_full['Outcome'] == majority_label]
#     # print(f"majority class count: {len(df_majority)}")

#     # # create metadata from the dataframe
#     metadata = SingleTableMetadata()
#     metadata.detect_from_dataframe(df_train_full)
#     print(f"{metadata}")
#     # metadata.save_to_json(fr'C:\Users\MABROUKAs\Downloads\IEEE-Access-2026\HardVAE\data\processed\{dataset_name}_metadata.json')

#     # instatiate the synthesizer

#     ## CTGAN
#     set_seed(seed) # set the seed for reproducibility
#     ctgan = CTGANSynthesizer(metadata, epochs=N_EPOCHS, batch_size=BATCH_SIZE, enable_gpu=True, verbose=True, pac=8)
#     ctgan.fit(df_minority) # -> fit only on the training data

#     ctgan_samples = ctgan.sample(n_samples_needed) # get number of samples needed to balance the training data
#     print(f"ctgan samples:\n{ctgan_samples.head(3)}")

#     # remove the `Outcome` column and re-add it
#     X_ctgan_raw = ctgan_samples.drop(columns=['Outcome'])
#     y_ctgan = np.full(len(X_ctgan_raw), minority_label)
#     print(f"head of the X_ctgan_raw {X_ctgan_raw.head()}")



#     # ## TVAE < will be our baseline since we use TVAE Now!
#     # tvae = TVAESynthesizer(metadata, epochs=N_EPOCHS, batch_size=BATCH_SIZE, enable_gpu=True, verbose=True)
#     # tvae.fit(df_minority) # -> fit only on the training minority data
#     # tvae_samples = tvae.sample(n_samples_needed) # get number of samples needed to balance the training data
#     # print(f"tvae samples:\n{tvae_samples.head(3)}")




#     # FIDELITY EVALUATION

#     # UTILITY EVLUATION

#     # STORE RESULTS

########## TabDDPM ##########
# check how to implement TabDDPM

######### TabSyn ###########
# check Tabsyn implementation in https://github.com/amazon-science/tabsyn/
# since our data is already preprocessed to have all variable with numerical values, we can directly use the preprocessed data to train TabSyn

# START WITH TABSYN according to its paper no tuning is made neither to the generator nor to the classifier.
## we can adopt this methodology! also check tabdiff for their paper methodology